### ISSUE TITLE
【Plugin submission】:: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corru...

### ISSUE THREAD

**Issue by zoulejiu** [mbtsp/mybatisSmartCodeHelp#8]
:warning:_`[Auto Generated Report]-=4A4FA75CF61EBEBE12D9FEBC733DE1EF=-`_
## Environments
> **Plugin version: 2023.1.0**

IntelliJ IDEA 2023.1.2"Ultimate Edition"
Build #IU-231.9011.34,built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Operating system: Windows 10.0
Last action id: Vcs.UpdateProject

## Stack Trace
```
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted C:\Users\wangshm02\AppData\Local\JetBrains\IntelliJIdea2023.1\index\stubs\.perFileVersion\indexed_versions\indexed_versions
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:615)
	at com.intellij.util.io.PersistentEnumeratorBase.valueOf(PersistentEnumeratorBase.java:426)
	at com.intellij.util.io.PersistentBTreeEnumerator.valueOf(PersistentBTreeEnumerator.java:733)
	at com.intellij.util.io.PersistentEnumeratorBase$1.process(PersistentEnumeratorBase.java:324)
	at com.intellij.util.io.PersistentBTreeEnumerator$3.process(PersistentBTreeEnumerator.java:378)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.lambda$processMappings$1(IntToIntBtree.java:629)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.processMappings(IntToIntBtree.java:632)
	at com.intellij.util.io.IntToIntBtree.processLeafPages(IntToIntBtree.java:1045)
	at com.intellij.util.io.IntToIntBtree.processMappings(IntToIntBtree.java:1040)
	at com.intellij.util.io.PersistentBTreeEnumerator.traverseAllRecords(PersistentBTreeEnumerator.java:372)
	at com.intellij.util.io.PersistentEnumeratorBase.processAllDataObject(PersistentEnumeratorBase.java:320)
	at com.intellij.util.io.PersistentBTreeEnumerator.processAllDataObject(PersistentBTreeEnumerator.java:363)
	at com.intellij.util.io.PersistentMapImpl.processExistingKeys(PersistentMapImpl.java:590)
	at com.intellij.util.io.PersistentHashMap.processKeysWithExistingMapping(PersistentHashMap.java:192)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator.valueOf(PersistentSubIndexerVersionEnumerator.java:85)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerRetriever.getVersionByIndexerId(PersistentSubIndexerRetriever.java:117)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.getStoredSubIndexerVersion(VfsAwareMapReduceIndex.java:235)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.determinePreviousFileElementType(PerFileElementTypeStubModificationTracker.java:197)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.fastCheck(PerFileElementTypeStubModificationTracker.java:101)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.lambda$endUpdatesBatch$2(PerFileElementTypeStubModificationTracker.java:76)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:59)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.endUpdatesBatch(PerFileElementTypeStubModificationTracker.java:75)
	at com.intellij.util.indexing.events.ChangedFilesCollector$4.endBatch(ChangedFilesCollector.java:246)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$endBatch$2(ChangedFilesCollector.java:283)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:258)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.endBatch(ChangedFilesCollector.java:282)
	at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:109)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:265)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:224)
	at com.intellij.util.indexing.events.ChangedFilesCollector.ensureUpToDate(ChangedFilesCollector.java:190)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:836)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:316)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFilesIterator(FileBasedIndexEx.java:263)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:239)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1169)
	at com.intellij.util.xml.DomFileIndex.findFiles(DomFileIndex.java:39)
	at com.intellij.util.xml.impl.DomServiceImpl.getDomFileCandidates(DomServiceImpl.java:171)
	at com.intellij.util.xml.impl.DomServiceImpl.getFileElements(DomServiceImpl.java:178)
	at com.mybatis.b.g.a(g.java)
	at com.mybatis.b.M.a(M.java)
	at com.mybatis.b.M.a(M.java)
	at com.mybatis.b.M.b(M.java)
	at com.mybatis.b.M.b(M.java)
	at com.mybatis.h.a.getIcon(a.java)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:91)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:87)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:87)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:43)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:310)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:228)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:86)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$3(DeferredIconImpl.java:228)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:93)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$6(DeferredIconImpl.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

````

**Comment by zoulejiu** [comment]
fix 2023.1.1
